### ISSUE TITLE
nested fragment call a new fragment!

### ISSUE THREAD

**Issue by MohsenShafiee** [googlesamples/android-SlidingTabsColors#1]
hi... I'm using this sliding tab... and i have separated fragment in every tab! this sliding tab in within a frame container in main activity!
now i want to replace new fragment from one child (tab) of this fragment! and set it to frame container! how can I do this?
thanks...

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
