### ISSUE TITLE
the SlidingTabLayout uses deprecated methods.

### ISSUE THREAD

**Issue by syslogic** [googlesamples/android-SlidingTabsColors#2]
`viewPager.setOnPageChangeListener(new InternalViewPagerListener());`
should be `viewPager.addOnPageChangeListener(new InternalViewPagerListener());`
... or probably determine, on which API it is running.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
